- CMakeLists.txt
- README.txt
- TMOCmd/TMOCmd.cpp
- TMOgui/TMOGUIFilters.cpp
- tmolib/freejpeghdr.cpp
Upraveny instrukce pro preklad, odstranen preklad problemovych balicku, odstranen include jpegint.h, ktery je povazovan za interni pro JPEG knihovnu a neni pro preklad potrebovan, upraveno volani konstruktoru QLineEdit.
> Odstraneny problemy s prekladem

- TMOAncuti16/CMakeLists.txt
- TMOAncuti16/TMOAncuti16.cpp
- TMOAncuti16/TMOAncuti16.h
Dobry den,
podarilo sa mi to vyriesit ten problem zo opencv namespaceom. Snad som to uz teraz dobre commitol, ospravedlnujem sa za svoju nepozoronost predtym.
> Naive fusion and opencv runnig, namespace problem resolved

- TMOAncuti16/TMOAncuti16.cpp
Zmena v tom ze sumovanie do 1 nie je pre normalizovane mapy ale pre vsetky laplacian a global weight maps
> output tweaks

- TMOSon14/TMOSon14.cpp
- TMOSon14/baseAndDetailDecomposition.cpp
- TMOSon14/baseAndDetailDecomposition.h
Nahrazení alespoň metody pro maximalizaci detailu pomocí jedné z knihoven pro kvadratické programování.
> Dotvoření stochastických metod pro optimalizaci

- CMakeLists.txt
- TMOBiswas05/CMakeLists.txt
- TMOBiswas05/TMOBiswas05.cpp
- TMOBiswas05/TMOBiswas05.h
- TMOBiswas05/TMOPlugin.cpp
- TMOBiswas05/TMOPlugin.h
Zdá se že funguje, jenom je pomalý asi kvůli mediánu.
> Biswas05 - Alpha version

- tmolib/TMOImage.cpp
- tmolib/TMOImage.h
Nakonec jsem to hodil do jedne fce, aby nebylo treba includovat libpng do .h souboru. Je tam navic dost spolecneho kodu tak by to bylo redundantni delit.
Jinak ukladani mam v 8it, je treba to menit? Nevim podle ceho bych to rozeznal protoze png pripona pokud vim se nemeni na 16bit.
Jinak mam jeste udelat to PPM? Jestli o to treba nemel zajem nekdo jiny jako projekt. :D
> Exceptions in TMOImage, 16bit loading

- TMOgui/tmoguiwindow.cpp
- tmolib/TMOImage.cpp
- tmolib/TMOImage.h
Je tam to PPM. Opet jsem tam dal moznost prepinace na 16bit export, jinak to uklada 8bit defaultne. Testoval jsem to na par obrazcich a zda se ze vse funguje.
> PPM and PNG 16/8bit completed

- tmolib/TMOImage.cpp
- tmolib/TMOImage.h
Tak je to snad opraveno. Prosim otestujte to jeste na necem Vasem. Zjistil jsem ze muj referencni png se jen hlavickou jako 16bit tvaril :D
> PPM ASCII support and PNG 16bit load fix

- TMOBiswas05/TMOBiswas05.cpp
- tmolib/TMOImage.cpp
- tmolib/TMOImage.h
Testoval jsem a opravil par malickosti. Jinak uz to snad docela jede :D Pokud na neco jeste prijdu tak commitnu.
> PNG grayscale fix, biswas range fix, comments

- TMOBiswas05/TMOBiswas05.cpp
Trochu jsem prepsal ten kod a opravil nesrovnalost, kterou jsem zjistil v tmocmd pri defaultnim nastaveni.
> Biswas v2.0

- TMOXiong17/TMOXiong17.cpp
pro nastavitelny order 1 to zatím nejde, ale jinak by to snad mělo fungovat
> opraven bug s horizontalnim obrazkem a nefunkcni power

- tmolib/TMOVideo.cpp
To, ze kazde video malo flickering sa mi zdalo zvlastne tak som sa na to pozrel a bola tam chyba v tom, ze som vystup normalizoval... a to tam byt nemalo malo tam byt len convert. Takze po tejto zmene je flickering uz len v 1-2 videach(vsetko som nanovo preratal).Zmenil som aj codek na H264 pretoze ten pretym robil prilis velke videa.
> Opraveny flickering

- TMOCLAHE/clahe.cpp
-- zbytečné proměnné odstraněny -- trochu oddechu od paměti
> clahe.cpp updated

- TMOCLAHE/TMOCLAHE.cpp
- TMOCLAHE/clahe.cpp
- TMOCLAHE/clahe.h
regionSize -- 7 - 999
-- linearni a bilinearni interpolace opravena
-- upravy na hranach
> upravy na hranach

- TMOTao17/CMakeLists.txt
- TMOTao17/TMOTao17.cpp
- TMOTao17/TMOTao17.h
- TMOTao17/include/GridCut/GridGraph_2D_4C.h
- TMOTao17/include/GridCut/GridGraph_2D_4C_MT.h
- TMOTao17/include/GridCut/GridGraph_2D_8C.h
- TMOTao17/include/GridCut/GridGraph_3D_26C.h
- TMOTao17/include/GridCut/GridGraph_3D_6C.h
- TMOTao17/include/GridCut/GridGraph_3D_6C_MT.h
Toto je posledna verzia Tao17 a tym padom by mali byt vsetky moje kody aktualne
> latest tao

- TMOAlsam06/CMakeLists.txt
- TMOAlsam06/TMOAlsam06.cpp
- TMOAlsam06/TMOAlsam06.h
- TMOAlsam06/TMOPlugin.cpp
- TMOAlsam06/TMOPlugin.h
Dobrý den,
měl jsem v repozitáři nějaké problémy s bílými znaky, proto jsem tam měl i soubory co jsem neupravoval. Nakonec jsem to celé smazal, použil Váš originál a přidal moji složku Alsam06, tak už by to snad mělo být v pořádku.
> Added Alsam06.

- CMakeLists.txt
- TMOEisemann04/CMakeLists.txt
- TMOEisemann04/TMOEisemann04.cpp
- TMOEisemann04/TMOEisemann04.h
- TMOEisemann04/TMOPlugin.cpp
- TMOEisemann04/TMOPlugin.h
xjaska00
Flash Photography Enhancement via Intrinsic Relighting
> TMOEisemann04

- TMOSon14/CMakeLists.txt
- TMOSon14/TMOSon14.cpp
- TMOSon14/TMOSon14.h
- TMOSon14/baseAndDetailDecomposition.cpp
- TMOSon14/qpOasesOptimalization.cpp
- TMOSon14/qpOasesOptimization.h
Zkontrolovány a případně opraveny
-- rozměry příslušných matic pro optimalizaci
-- vkládání a nastavení prvků do matic
-- "rozhodovací" mapa pro nastavení hodnoty prvků
-- způsob ukládání stylem row-wise do 1D, tj. po řádcích
-- link na ukázkový obrázek v sekvenci po 0.1 vylepšení
-- http://leteckaposta.cz/702400855
-- rozměry + způsob vkládání zkontrolován a případně opraven podle detail.m
> Final Version

- TMOJin17/CMakeLists.txt
It's needed because the code requires mlpack/core/optimizers/function.hpp
but that one was introduced in mlpack 3.0.0.
Also do some cosmetic changes while touching the file.
> Add check for the mlpack version

- TMOKou15/L0minimization.cpp
- TMOKou15/L0minimization.h
- TMOKou15/TMOKou15.cpp
- TMOKou15/TMOKou15.h
added parameters, output put to <0,1> and some final minor changes
> Method Kou15 is complete

- TMOFarbman08/TMOFarbman08.cpp
- TMOFarbman08/TMOFarbman08.h
output to <0,1> range + cosmetic changes
> Method Farbman08 is complete

- TMOAubry14/CMakeLists.txt
- TMOAubry14/FastLocalLaplFilt.cpp
- TMOAubry14/FastLocalLaplFilt.h
- TMOAubry14/TMOAubry14.cpp
- TMOAubry14/TMOAubry14.h
added HDR support, reorganized code
> Method Aubry14 is complete

- CMakeLists.txt
- TMOSon14/CMakeLists.txt
- TMOSon14/TMOSon14.cpp
also changes in method's and its parameters' names
> fixed cmakelists - osqp library added

- TMOSon14/L0minimization.cpp
- TMOSon14/L0minimization.h
- TMOSon14/TMOSon14.cpp
- TMOSon14/TMOSon14.h
- TMOSon14/baseAndDetailDecomposition.cpp
- TMOSon14/baseAndDetailDecomposition.h
- TMOSon14/constructQpMatrices.cpp
- TMOSon14/constructQpMatrices.h
- TMOSon14/osqpOptimization.cpp
- TMOSon14/osqpOptimization.h
comment out unused code, remove unnecessary code, added headers to source files
> cleanup and authorship of Son14

- TMOgui/TMOGUIAdjust.cpp
- TMOgui/TMOGUIBitmap.cpp
- TMOgui/TMOGUIHisto.cpp
- TMOgui/TMOGUIImage.cpp
- TMOgui/TMOGUIInfoPanel.cpp
- TMOgui/TMOGUIMenu.cpp
- TMOgui/TMOGUIMenu.h
- TMOgui/TMOGUIProgressBar.h
- TMOgui/TMOGUISaveDialog.cpp
- TMOgui/TMOGUIStatus.h
- TMOgui/TMOGUIZoomTool.cpp
- TMOgui/icons.qrc
- TMOgui/main.cpp
- TMOgui/tmoguiwindow.cpp
- TMOgui/tmoguiwindow.h
Fixed bugs with opening and saving images, minor tweaks in toolbar, menu and info panel. Refresh of histogram after transformation.
> GUI bug fixes

- CMakeLists.txt
- TMOTai08/CMakeLists.txt
- TMOTai08/TMOPlugin.cpp
- TMOTai08/TMOPlugin.h
- TMOTai08/TMOTai08.cpp
- TMOTai08/TMOTai08.h
* https://doi.org/10.1109/CISP.2008.400
* note that dynamic range normalization is guessed, as it is not a part
of the original article
> Implemented "A Two-Stage Contrast Enhancement Algorithm for Digital Images"

- CMakeLists.txt
- TMODrago03/CMakeLists.txt
- TMODrago03/TMODrago03.cpp
- TMODrago03/TMODrago03.h
- TMODrago03/TMOPlugin.cpp
- TMODrago03/TMOPlugin.h
- tmolib/TMOImage.cpp
- tmolib/TMOImage.h
Add article implementation: Adaptive Logarithmic Mapping For Displaying High Contrast Scenes (Drago 2003)
> Add Drago03 TMO

- TMOShan10/CMakeLists.txt
- TMOShan10/MatUtil.cpp
- TMOShan10/MatUtil.h
- TMOShan10/TMOShan10.cpp
- TMOShan10/TMOShan10.h
This pull request adds solving a large linear system based
on the article: Globally Optimized Linear Windowed Tone-Mapping.
> TMOShan10: Add solving the linear system

- TMOShan10/CMakeLists.txt
- TMOShan10/MatUtil.cpp
- TMOShan10/MatUtil.h
- TMOShan10/TMOShan10.cpp
- TMOShan10/TMOShan10.h
- TMOShan10/cmake/FindEigen.cmake
- TMOShan10/imresize/README.md
- TMOShan10/imresize/image_processing.h
- TMOShan10/imresize/imresize.h
- TMOShan10/imresize/matrix_computations.h
- tmolib/TMOImage.cpp
- tmolib/TMOImage.h
Solving the linear system is reimplemented for using the Eigen library.
The Eigen library offers more options for the Sparse matrix
and optimizes the processing. The implementation of the OpenCV resize
function is replaced by the implementation of the original
MATLAB imresize function written in C language. In this pull request,
the bugs are fixed too.
> TMOShan10: solving linear system using Eigen

- CMakeLists.txt
- TMOLiu15/CMakeLists.txt
- TMOLiu15/TMOLiu15.cpp
- TMOLiu15/TMOLiu15.h
- TMOLiu15/TMOPlugin.cpp
- TMOLiu15/TMOPlugin.h
Implementation of: Gradient correlation similarity for efficient contrast preserving decolorization - **GcsDecolor2**
Rewritten from Matlab to c++.
Credit: https://github.com/yqx7150/GcsDecolor
Examples:
> Implementation of Liu15
